name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    name: Frontend Build Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontened

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Next.js App
        run: bun run build

  backend-build-test:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.2"
          cache: true
          cache-dependency-path: backend/go.mod

      - name: Run Go Tests
        run: go test -v ./...

      - name: Build Go App
        run: go build -v ./...
